name: "Kogito Tooling :: Build chain"

on: [pull_request]

jobs:
  build-chain:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install takari
        run: |
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/aether/takari-local-repository/0.11.3/takari-local-repository-0.11.3.jar
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/takari-filemanager/0.8.3/takari-filemanager-0.8.3.jar
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/maven/takari-smart-builder/0.6.1/takari-smart-builder-0.6.1.jar
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@v2.4
        with:
          starting-project: kiegroup/kogito-tooling
          definition-file: https://raw.githubusercontent.com/tiagobento/kogito-online-ci/gh-actions-kogito-tooling-checks-v7/.ci/kogito-tooling-pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"